
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package lenguag.syntactic;

/** CUP generated class containing symbol constants. */
public class ParserSym {
  /* terminals */
  public static final int TYPE_BOOLEAN = 8;
  public static final int L_KEY = 16;
  public static final int EQUALS = 31;
  public static final int RES_ELSE = 10;
  public static final int L_PAREN = 14;
  public static final int INTEGER = 38;
  public static final int R_PAREN = 15;
  public static final int CHARACTER = 40;
  public static final int NOT = 4;
  public static final int AND = 30;
  public static final int RES_FOR = 12;
  public static final int RES_WHILE = 11;
  public static final int OR = 29;
  public static final int COMMA = 21;
  public static final int ENDLINE = 22;
  public static final int DIV = 27;
  public static final int R_KEY = 17;
  public static final int OP_SWAP = 23;
  public static final int LESSER = 34;
  public static final int R_BRACKET = 19;
  public static final int BOOLEAN = 41;
  public static final int EOF = 0;
  public static final int EQUAL = 20;
  public static final int error = 1;
  public static final int ADD = 24;
  public static final int MOD = 28;
  public static final int NEQ = 36;
  public static final int CONSTANT = 3;
  public static final int BIGGER = 32;
  public static final int TYPE_FLOAT = 6;
  public static final int RES_RETURN = 13;
  public static final int TYPE_INTEGER = 5;
  public static final int FLOAT = 39;
  public static final int LEQ = 35;
  public static final int PROD = 26;
  public static final int RES_MAIN = 2;
  public static final int TYPE_CHARACTER = 7;
  public static final int L_BRACKET = 18;
  public static final int RES_IF = 9;
  public static final int SUB = 25;
  public static final int BEQ = 33;
  public static final int IDENTIFIER = 37;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "RES_MAIN",
  "CONSTANT",
  "NOT",
  "TYPE_INTEGER",
  "TYPE_FLOAT",
  "TYPE_CHARACTER",
  "TYPE_BOOLEAN",
  "RES_IF",
  "RES_ELSE",
  "RES_WHILE",
  "RES_FOR",
  "RES_RETURN",
  "L_PAREN",
  "R_PAREN",
  "L_KEY",
  "R_KEY",
  "L_BRACKET",
  "R_BRACKET",
  "EQUAL",
  "COMMA",
  "ENDLINE",
  "OP_SWAP",
  "ADD",
  "SUB",
  "PROD",
  "DIV",
  "MOD",
  "OR",
  "AND",
  "EQUALS",
  "BIGGER",
  "BEQ",
  "LESSER",
  "LEQ",
  "NEQ",
  "IDENTIFIER",
  "INTEGER",
  "FLOAT",
  "CHARACTER",
  "BOOLEAN"
  };
}

