/* The following code was generated by JFlex 1.6.1 */

/**
 * Asignatura: 21780 - Compiladores
 * Miembros:
 * 	- Korn, Andreas Manuel
 * 	- Román Colom, Marc
 * 	- Vilella Candia, Joan 
 */
// Si estás en Lexic.java, OJO! Este archivo no debe ser modificado manualmente: para hacer cambios hacerlo en lenguaG.flex 
// y luego seleccionar dicho archivo como input de jflex en "lexical specification". El output se debe dejar tal cual.

package lenguag.lexic;

// Other libraries
//import java.io.*;
import java.util.*;
import java_cup.runtime.ComplexSymbolFactory.ComplexSymbol;
import java_cup.runtime.ComplexSymbolFactory.Location;

// Our project imports
import lenguag.syntactic.ParserSym;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>lenguag/lexic/lenguaG.flex</tt>
 */
public class Lexic implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\52\1\54\1\55\1\55\1\54\22\0\1\52\1\51\1\0"+
    "\1\53\1\0\1\50\1\0\1\0\1\31\1\32\1\46\1\44\1\40"+
    "\1\45\1\0\1\47\1\3\1\5\6\7\2\2\1\0\1\37\1\42"+
    "\1\41\1\43\2\0\6\11\24\1\1\35\1\0\1\36\1\0\1\1"+
    "\1\0\1\21\1\4\1\11\1\17\1\24\1\25\1\1\1\30\1\12"+
    "\2\1\1\15\1\20\1\13\1\6\2\1\1\22\1\26\1\14\1\23"+
    "\1\16\1\27\1\10\2\1\1\33\1\0\1\34\7\0\1\55\u1fa2\0"+
    "\1\55\1\55\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\2\3\14\2\1\4\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\1\1\1\24\1\25"+
    "\3\0\1\2\1\26\1\2\1\27\1\30\13\2\1\31"+
    "\1\32\1\0\1\33\1\0\1\34\3\3\1\2\1\35"+
    "\1\36\1\37\2\2\1\40\1\2\1\41\2\2\1\42"+
    "\2\2\2\0\1\43\1\44\1\45\1\46\1\2\1\47"+
    "\1\2\1\50\1\25\1\2\1\51\1\52";

  private static int [] zzUnpackAction() {
    int [] result = new int[92];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\56\0\134\0\212\0\270\0\346\0\u0114\0\u0142"+
    "\0\u0170\0\u019e\0\u01cc\0\u01fa\0\u0228\0\u0256\0\u0284\0\u02b2"+
    "\0\u02e0\0\56\0\56\0\56\0\56\0\56\0\56\0\56"+
    "\0\56\0\u030e\0\u033c\0\u036a\0\56\0\56\0\56\0\u0398"+
    "\0\56\0\u03c6\0\u03f4\0\u0422\0\u0450\0\u047e\0\u04ac\0\u04da"+
    "\0\134\0\u0508\0\u0536\0\134\0\u0564\0\u0592\0\u05c0\0\u05ee"+
    "\0\u061c\0\u064a\0\u0678\0\u06a6\0\u06d4\0\u0702\0\u0730\0\56"+
    "\0\56\0\u075e\0\56\0\u078c\0\56\0\u0450\0\u047e\0\u04ac"+
    "\0\u07ba\0\134\0\134\0\134\0\u07e8\0\u0816\0\134\0\u0844"+
    "\0\134\0\u0872\0\u08a0\0\134\0\u08ce\0\u08fc\0\u092a\0\u0958"+
    "\0\134\0\134\0\134\0\134\0\u0986\0\134\0\u09b4\0\56"+
    "\0\u078c\0\u09e2\0\134\0\134";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[92];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\4\1\7\1\4"+
    "\2\3\1\10\1\11\1\12\1\3\1\13\1\3\1\14"+
    "\1\15\1\16\1\3\1\17\1\20\1\3\1\21\1\3"+
    "\1\22\1\23\1\24\1\25\1\26\1\27\1\30\1\31"+
    "\1\32\1\33\1\34\1\35\1\36\1\37\1\40\1\41"+
    "\1\42\1\43\1\44\1\43\1\2\57\0\30\3\27\0"+
    "\2\4\1\0\1\4\1\0\1\4\52\0\1\45\1\0"+
    "\1\46\1\0\1\47\46\0\5\3\1\50\22\3\26\0"+
    "\21\3\1\51\1\52\5\3\26\0\12\3\1\53\11\3"+
    "\1\54\3\3\26\0\5\3\1\55\22\3\26\0\21\3"+
    "\1\56\6\3\26\0\5\3\1\57\12\3\1\60\7\3"+
    "\26\0\20\3\1\61\7\3\26\0\12\3\1\62\15\3"+
    "\26\0\23\3\1\63\4\3\26\0\14\3\1\64\13\3"+
    "\26\0\5\3\1\65\12\3\1\66\7\3\26\0\27\3"+
    "\1\67\66\0\1\70\55\0\1\71\1\72\54\0\1\73"+
    "\62\0\1\74\1\44\47\0\1\75\66\0\1\43\1\0"+
    "\1\43\1\0\54\44\5\0\1\76\1\0\1\76\53\0"+
    "\1\77\1\0\1\77\1\0\1\77\50\0\4\100\1\0"+
    "\1\100\1\0\1\100\5\0\1\100\1\0\1\100\2\0"+
    "\2\100\31\0\5\3\1\101\22\3\26\0\13\3\1\102"+
    "\14\3\26\0\13\3\1\103\14\3\26\0\13\3\1\104"+
    "\14\3\26\0\22\3\1\105\5\3\26\0\11\3\1\106"+
    "\16\3\26\0\14\3\1\107\13\3\26\0\11\3\1\110"+
    "\16\3\26\0\16\3\1\111\11\3\26\0\13\3\1\112"+
    "\14\3\26\0\25\3\1\113\2\3\26\0\21\3\1\114"+
    "\6\3\26\0\14\3\1\115\13\3\26\0\11\3\1\116"+
    "\16\3\70\0\1\117\12\0\46\74\1\120\7\74\1\0"+
    "\14\3\1\121\13\3\26\0\23\3\1\122\4\3\26\0"+
    "\16\3\1\123\11\3\26\0\12\3\1\124\15\3\26\0"+
    "\22\3\1\125\5\3\26\0\23\3\1\126\4\3\26\0"+
    "\25\3\1\105\2\3\26\0\14\3\1\127\13\3\70\0"+
    "\1\130\12\0\46\74\1\120\1\131\6\74\1\0\21\3"+
    "\1\132\6\3\26\0\23\3\1\133\4\3\26\0\12\3"+
    "\1\134\15\3\25\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[2576];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\17\1\10\11\3\1\3\11\1\1\1\11"+
    "\3\1\3\0\20\1\2\11\1\0\1\11\1\0\1\11"+
    "\21\1\2\0\7\1\1\11\4\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[92];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
	private ArrayList<String> tokens = new ArrayList<>();
	private ArrayList<String> errors = new ArrayList<>();

	/* private void addTokens(String token){
		tokens.add(token);
	} */

	public String writeTokens(){
		String tokenList = "";

		for(String s : tokens){
			tokenList += s + "\n";
		}

		return tokenList;
	}

	public String writeErrors(){
		String errorsList = "";

		for(String s : errors){
			errorsList += s + "\n";
		}

		return errorsList;
	}

	public boolean thereIsError(){
		return !errors.isEmpty();
	}

	private String errorMessage(){
		return " !! Lexic error: Not recognized token " + yytext() + " at position [line: " + (yyline+1) + ", column: " + (yycolumn+1) + "]";
	}
	
	private int parseNum(String s) throws NumberFormatException {
		// We check whether the first number is a 0, if so there might be a prefix specifying base, unless it's just a 0 by itself.
		if(s.charAt(0) != '0' || s.length() == 1) return Integer.parseInt(s);
		// If 
		char base = s.charAt(1);
		String num = s.substring(2);
		//String[] sParts = s.split(""+base);
		switch(base){
			case 'b':
				return Integer.parseInt(num, 2);
			case 'o':
				return Integer.parseInt(num, 8);
			case 'x':
				return Integer.parseInt(num, 16);
			default:
				throw new NumberFormatException(errorMessage());
		}
	}

	// Functions to streamline CUP symbol returns.
    private ComplexSymbol symbol(int type) {
        Location l = new Location(yyline+1, yycolumn+1);
        Location r = new Location(yyline+1, yycolumn+yylength());
        return new ComplexSymbol(ParserSym.terminalNames[type], type, l, r);
        //return new ComplexSymbol(type, yyline+1, yycolumn+1);
    }
    
    private ComplexSymbol symbol(int type, Object value) {
        Location l = new Location(yyline+1, yycolumn+1);
        Location r = new Location(yyline+1, yycolumn+yylength());
        return new ComplexSymbol(ParserSym.terminalNames[type], type, l, r, value);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexic(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 178) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { 	return symbol(ParserSym.EOF);
 }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { errors.add(errorMessage()); System.err.println(errorMessage());
						return symbol(ParserSym.error);
            }
          case 43: break;
          case 2: 
            { tokens.add(yytext() + " : IDENTIFIER"); return symbol(ParserSym.IDENTIFIER, yytext());
            }
          case 44: break;
          case 3: 
            { try {
							Integer value = parseNum(yytext()); 
							tokens.add(yytext() + " : INTEGER"); 
							return symbol(ParserSym.INTEGER, value); 
						} catch(NumberFormatException nf) {
							errors.add(errorMessage()); System.err.println(errorMessage());
							return symbol(ParserSym.error);
						}
            }
          case 45: break;
          case 4: 
            { tokens.add(yytext() + " : L_PAREN"); return symbol(ParserSym.L_PAREN);
            }
          case 46: break;
          case 5: 
            { tokens.add(yytext() + " : R_PAREN"); return symbol(ParserSym.R_PAREN);
            }
          case 47: break;
          case 6: 
            { tokens.add(yytext() + " : L_KEY"); return symbol(ParserSym.L_KEY);
            }
          case 48: break;
          case 7: 
            { tokens.add(yytext() + " : R_KEY"); return symbol(ParserSym.R_KEY);
            }
          case 49: break;
          case 8: 
            { tokens.add(yytext() + " : L_BRACKET"); return symbol(ParserSym.L_BRACKET);
            }
          case 50: break;
          case 9: 
            { tokens.add(yytext() + " : R_BRACKET"); return symbol(ParserSym.R_BRACKET);
            }
          case 51: break;
          case 10: 
            { tokens.add(yytext() + " : ENDLINE"); return symbol(ParserSym.ENDLINE);
            }
          case 52: break;
          case 11: 
            { tokens.add(yytext() + " : COMMA"); return symbol(ParserSym.COMMA);
            }
          case 53: break;
          case 12: 
            { tokens.add(yytext() + " : EQUAL"); return symbol(ParserSym.EQUAL);
            }
          case 54: break;
          case 13: 
            { tokens.add(yytext() + " : LESSER"); return symbol(ParserSym.LESSER);
            }
          case 55: break;
          case 14: 
            { tokens.add(yytext() + " : BIGGER"); return symbol(ParserSym.BIGGER);
            }
          case 56: break;
          case 15: 
            { tokens.add(yytext() + " : ADD"); return symbol(ParserSym.ADD);
            }
          case 57: break;
          case 16: 
            { tokens.add(yytext() + " : SUB"); return symbol(ParserSym.SUB);
            }
          case 58: break;
          case 17: 
            { tokens.add(yytext() + " : PROD"); return symbol(ParserSym.PROD);
            }
          case 59: break;
          case 18: 
            { tokens.add(yytext() + " : DIV"); return symbol(ParserSym.DIV);
            }
          case 60: break;
          case 19: 
            { tokens.add(yytext() + " : MOD"); return symbol(ParserSym.MOD);
            }
          case 61: break;
          case 20: 
            { /* Do nothing */
            }
          case 62: break;
          case 21: 
            { /* We fully ignore comments */
            }
          case 63: break;
          case 22: 
            { tokens.add(yytext() + " : OR"); return symbol(ParserSym.OR);
            }
          case 64: break;
          case 23: 
            { tokens.add(yytext() + " : RES_IN"); return symbol(ParserSym.RES_IN);
            }
          case 65: break;
          case 24: 
            { tokens.add(yytext() + " : RES_IF"); return symbol(ParserSym.RES_IF);
            }
          case 66: break;
          case 25: 
            { tokens.add(yytext() + " : IS_EQUAL"); return symbol(ParserSym.IS_EQUAL);
            }
          case 67: break;
          case 26: 
            { tokens.add(yytext() + " : LEQ"); return symbol(ParserSym.LEQ);
            }
          case 68: break;
          case 27: 
            { tokens.add(yytext() + " : BEQ"); return symbol(ParserSym.BEQ);
            }
          case 69: break;
          case 28: 
            { tokens.add(yytext() + " : NEQ"); return symbol(ParserSym.NEQ);
            }
          case 70: break;
          case 29: 
            { tokens.add(yytext() + " : RES_OUT"); return symbol(ParserSym.RES_OUT);
            }
          case 71: break;
          case 30: 
            { tokens.add(yytext() + " : TYPE_INTEGER"); return symbol(ParserSym.TYPE_INTEGER);
            }
          case 72: break;
          case 31: 
            { tokens.add(yytext() + " : NOT"); return symbol(ParserSym.NOT);
            }
          case 73: break;
          case 32: 
            { tokens.add(yytext() + " : CONSTANT"); return symbol(ParserSym.CONSTANT);
            }
          case 74: break;
          case 33: 
            { tokens.add(yytext() + " : AND"); return symbol(ParserSym.AND);
            }
          case 75: break;
          case 34: 
            { tokens.add(yytext() + " : RES_FOR"); return symbol(ParserSym.RES_FOR);
            }
          case 76: break;
          case 35: 
            { tokens.add(yytext() + " : TYPE_BOOLEAN"); return symbol(ParserSym.TYPE_BOOLEAN);
            }
          case 77: break;
          case 36: 
            { tokens.add(yytext() + " : BOOLEAN"); return symbol(ParserSym.BOOLEAN, Boolean.parseBoolean(yytext()));
            }
          case 78: break;
          case 37: 
            { tokens.add(yytext() + " : TYPE_VOID"); return symbol(ParserSym.TYPE_VOID);
            }
          case 79: break;
          case 38: 
            { tokens.add(yytext() + " : RES_MAIN"); return symbol(ParserSym.RES_MAIN);
            }
          case 80: break;
          case 39: 
            { tokens.add(yytext() + " : RES_ELSE"); return symbol(ParserSym.RES_ELSE);
            }
          case 81: break;
          case 40: 
            { tokens.add(yytext() + " : OP_SWAP"); return symbol(ParserSym.OP_SWAP);
            }
          case 82: break;
          case 41: 
            { tokens.add(yytext() + " : RES_WHILE"); return symbol(ParserSym.RES_WHILE);
            }
          case 83: break;
          case 42: 
            { tokens.add(yytext() + " : RES_RETURN"); return symbol(ParserSym.RES_RETURN);
            }
          case 84: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
